name: musify_fork
description: Music Streaming app made in Flutter!
homepage: https://github.com/Ruchan10/Musify_fork
repository: https://github.com/gokadzev/Musify
issue_tracker: https://github.com/gokadzev/Musify/issues

publish_to: 'none'
version: 9.5.3+133 # run update.sh after changing the version

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ^3.32.2

dependencies:
  app_links: ^6.4.0
  audio_service: ^0.18.18
  audio_session: ^0.1.25
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  dynamic_color: ^1.7.0
  file_picker: ^10.1.9
  fluentui_system_icons: ^1.1.273
  flutter:
    sdk: flutter
  flutter_downloader: ^1.12.0
  flutter_flip_card: ^0.0.6
  flutter_localizations:
    sdk: flutter
  flutter_media_metadata: 
    path: ./packages/flutter_media_metadata
  go_router: ^14.8.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.5
  http: ^1.3.0
  just_audio: ^0.9.46
  on_audio_query: 
    path: ./packages/on_audio_query
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  phone_state: ^2.1.1
  rxdart: ^0.28.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  youtube_explode_dart:
    git:
      url: https://github.com/gokadzev/yt_explode_dart
      ref: OG

dev_dependencies:
  flutter_test:
    sdk: flutter
  translations_cleaner: ^0.0.5

  # flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/licenses/
    - assets/images/

  fonts:
    - family: paytoneOne
      fonts:
        - asset: fonts/paytone/PaytoneOne-Regular.ttf

flutter_native_splash:
  color: '#f9fafd'
  image: assets/images/ic_splash.png
  color_dark: '#151515'
  image_dark: assets/images/ic_splash.png

  android_12:
    image: assets/images/ic_splash.png
    image_dark: assets/images/ic_splash.png

flutter_launcher_icons:
  android: true
  adaptive_icon_background: '#191919'
  adaptive_icon_foreground: 'assets/images/ic_launcher_foreground.png'
  adaptive_icon_round: 'assets/images/ic_launcher_round.png'
  adaptive_icon_monochrome: 'assets/images/ic_launcher_foreground.png'
  image_path: 'assets/images/ic_launcher.png'
